apiVersion: apps/v1
kind: Deployment
metadata:
  name: bffweb-deployment
spec:
  selector:
    matchLabels:
      app: bffweb-pod
  template:
    metadata:
      labels:
        app: bffweb-pod
    spec:
      containers:
      - name: bffweb-container
        image: mahedee/bff.web:1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: bffweb-service
spec:
  selector:
    app: bffweb-pod
  ports:
  - port: 8011
    targetPort: 80
  type: LoadBalancer
