apiVersion: apps/v1
kind: Deployment
metadata:
  name: locationapi-deployment
spec:
  selector:
    matchLabels:
      app: locationapi-pod
  template:
    metadata:
      labels:
        app: locationapi-pod
    spec:
      containers:
      - name: locationapi-container
        image: mahedee/location:1.0.1
        resources:
          limits:
            memory: "128Mi" # 128 mili bytes
            cpu: "500m"     # 500 mili cpu
        ports:
        - containerPort: 80
